services:
  image-hosting-storage:
    container_name: image-hosting-storage
    image: image-hosting-storage
    build:
      context: .
      dockerfile: ImageHosting.Storage/Dockerfile
    environment:
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      Logging__LogLevel__Microsoft.EntityFrameworkCore: Warning
      Minio__Endpoint: images-s3:9000
      Minio__AccessKey: minioadmin
      Minio__SecretKey: minioadmin
      Minio__Secure: false
      ConnectionStrings__ImageHosting: "Host=metadata-db;Port=5432;Database=image_hosting;Username=image_hosting;Password=P@ssw0rd;Include Error Detail=true"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      images-s3:
        condition: service_started
      metadata-db:
        condition: service_healthy
  
  images-s3:
    container_name: images-s3
    image: quay.io/minio/minio:RELEASE.2024-01-31T20-20-33Z
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - images-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  
  metadata-db:
    container_name: metadata-db
    image: postgres:16-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: image_hosting
      POSTGRES_USER: image_hosting
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "image_hosting", "-U", "image_hosting" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  images-data:
  db-data:
