services:
  image-hosting-storage:
    container_name: image-hosting-storage
    image: ghcr.io/baklanov-soft/image-hosting-storage
    build:
      context: .
      dockerfile: ImageHosting.Storage/Dockerfile
    environment:
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      Logging__LogLevel__Microsoft.EntityFrameworkCore: Warning
      Minio__Endpoint: images-s3:9000
      Minio__AccessKey: minioadmin
      Minio__SecretKey: minioadmin
      Minio__Secure: false
      ConnectionStrings__ImageHosting: "Host=metadata-db;Port=5432;Database=image_hosting;Username=image_hosting;Password=P@ssw0rd;Include Error Detail=true"
      ASPNETCORE_ENVIRONMENT: Development
      Kafka__Producer__BootstrapServers: kafka:9092
      Kafka__Producer__ClientId: image-hosting-storage
      Kafka__Producer__CompressionType: gzip
      Kafka__NewImageTopic: new-images.v1
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      images-s3:
        condition: service_started
      metadata-db:
        condition: service_healthy
      kafka:
        condition: service_started
  
  images-s3:
    container_name: images-s3
    image: quay.io/minio/minio:RELEASE.2024-01-31T20-20-33Z
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - images-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  
  metadata-db:
    container_name: metadata-db
    image: postgres:16-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: image_hosting
      POSTGRES_USER: image_hosting
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "image_hosting", "-U", "image_hosting" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6.1
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: LelM2dIFQkiUFvXCEcqRWA
  
  kafka-init:
    container_name: kafka-init
    image: bitnami/kafka:3.6.1
    depends_on:
      - kafka
    entrypoint: "kafka-topics.sh"
    command: [
      "--bootstrap-server", "kafka:9092",
      "--create",
      "--replication-factor", "1",
      "--partitions", "2",
      "--topic", "new-images.v1"
    ]
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      SERVER_PORT: 8000
      KAFKA_CLUSTERS_0_NAME: image-hosting
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: true
    depends_on:
      - kafka

volumes:
  images-data:
  db-data:
