name: Upload test coverage report to codecov

on:
  push:
    branches: [ "master" ]

jobs:
  codecov:
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        working-directory: ./tests/ImageHosting.Storage.UnitTests
        run: dotnet restore

      - name: Build
        working-directory: ./tests/ImageHosting.Storage.UnitTests
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        working-directory: ./tests/ImageHosting.Storage.UnitTests
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          directory: ./tests/ImageHosting.Storage.UnitTests
          file: coverage.opencover.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          